sudo: false
language: java
jdk:
- oraclejdk8
env:
  global:
  - JSOCKET_USERNAME=deployer
  - secure: bpwhDfN6TlBQjr8C8f3mFcyqLFtUwJa+ehoCCYoUXDVdEiyZXPGwLt9ma/fyTc+lb185mV4I8N5E0h7k0QiLuH0g4Q/PG7UuzIOj7TmjpqRr5Y6eJ0NhbvIdtFy9VKT6XWlsQI8LqUnAnH3anIkE11hiR/iN+P9Z9cCDMBA6E5CzLwqoEhLMVV+yrYJIfvNNoIl76tSt4NtLcJpOBlj6QaaePNfGZaZ1jaPdzTKoRTIyUbiEYHNpJK0XXr5pfiq2wA9uAuetxRsTPyAEyrHtfIPuVYWOq8Fv/03CAUfGL5b52KMTPBOqGaAWcdfGgtTNrPbhat7WMgh24Aw8YTiqfN4wF7giQC4tBWEJPsEs1MfZxC3MNu3C8DFj/ojp15xiBgyVcgi+Bv9ENCF4bz2zmmQS4YdX2gKUlNGCvcFOROUjGMZcdAAjuD6kcyJuzwTFKOCp43uFuTLLeaYbdKUobTobmXc5dQ9VUdh2VitMhzleYmj3m3zFlOaWN5icYE67A1rtEaQiK3rd+k/Ezf4R3qGRymrHvNOcIDf9ROv4+ZmN31d5TwPplko0nr2YTGv5FFGvPilXY65b52y8OuAFncr3drEgu5ZeOuGNXnVLTDzXuUFimlj/vAIBxnU54KsLrcD479LPpuDgsbTrkD+mQepIHNz7wZvm2oUD+S0HWIQ=

before_install: mvn install -DskipTests=true
script: mvn test
#after_success: python deploy.py
